spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  flyway:
    enabled: false

jwt:
  secret: dGVzdC1zZWNyZXQta2V5LWZvci1oZWFsdGhpZXItYXBwLXRlc3RpbmctcHVycG9zZS1vbmx5
  access-expiry: 3600000
  refresh-expiry: 1209600000
